version: 2.1
jobs:
    trial:
      docker:
            - image: cimg/node:18.2.0
      parallelism: 2
      steps:
        - run:
            name: "trial"
            command: sudo apt update && sudo apt install lynx && lynx -dont_wrap_pre -dump


workflows:
    version: 2.1
    build:
        jobs:
        - trial
